language: cpp

dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial -y
  - sudo apt-get update
  - sudo apt-get install mesa-common-dev -y
  - sudo apt-get install qt510-meta-minimal -y

script:
  - source /opt/qt510/bin/qt510-env.sh
  - cmake .
  - make -j2
